---
- hosts: servers
  become: yes
  gather_facts: yes
  vars:
    mysql_root_password: "rooteado"

  collections:
   - community.mysql
  
  tasks:
  - name: Instalar PyMySQL en el nodo remoto
    ansible.builtin.apt:
     name: python3-pymysql
     state: present
     update_cache: yes

  roles:
   - php
   - mysql

 
      